GET http://localhost:3000
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2MDA3MTgwMjIsImV4cCI6MTYwMDgwNDQyMiwiYXVkIjoiNWY2OTAzOWJjNmQ1YjQwYjQ4YWYzMTUxIiwiaXNzIjoibWguandhZXJAZ21haWwuY29tIn0.Wp7QlCV2mcSt1HyJOCtGBGnR-pq9CfWsRBbGvkg-WlU




### register route
POST http://localhost:3000/auth/register
Content-Type: application/json

{
    "email": "mhj3@gmail.com",
    "password": "123546"
}


### login route
POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "email": "mhj2@gmail.com",
    "password": "123546"
}


###refresh token
POST http://localhost:3000/auth/refresh-token
Content-Type: application/json

{
    "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2MDA3MTc3ODAsImV4cCI6MTYzMjI3NTM4MCwiYXVkIjoiNWY2OTAzOWJjNmQ1YjQwYjQ4YWYzMTUxIiwiaXNzIjoibWguandhZXJAZ21haWwuY29tIn0.WVRVF3p8xgD3SRnVBUJgVlMhUsMtp7rBkR4ADYGDqlc"
}


###logout rout
DELETE  http://localhost:3000/auth/logout
Content-Type: application/json

{
    "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2MDA3MTc4MDEsImV4cCI6MTYzMjI3NTQwMSwiYXVkIjoiNWY2OTAzOWJjNmQ1YjQwYjQ4YWYzMTUxIiwiaXNzIjoibWguandhZXJAZ21haWwuY29tIn0.YxXzXLZ67vSmmiNvOl8Qu6zRY_rFcvu5anIhuHmxQeA"
}


###Create Circle
GET http://localhost:3000/circle/create
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2MDMxODk4NjgsImV4cCI6MTYwMzc5NDY2OCwiYXVkIjoiNWY4ZWJjNmNkYTFjMzAxMTBjOTQ2MmZmIiwiaXNzIjoibWguandhZXJAZ21haWwuY29tIn0.f53MZsGaN8cSD71D5r6xITbNzQTGlohb_PYh1mg4-_Q



###Join Circle
POST http://localhost:3000/circle/join/NLPNLI
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2MDMxOTExMDksImV4cCI6MTYwMzc5NTkwOSwiYXVkIjoiNWY4ZWMxNDVkYTFjMzAxMTBjOTQ2MzAyIiwiaXNzIjoibWguandhZXJAZ21haWwuY29tIn0.qz4gZAG6h10fFrcQ20buTiK7MBlBgJC2z-VBLENroYo




###save user name
POST http://localhost:3000/user/save-username/Mohammed
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2MDMxOTAwOTQsImV4cCI6MTYwMzc5NDg5NCwiYXVkIjoiNWY4ZWJkNGVkYTFjMzAxMTBjOTQ2MzAwIiwiaXNzIjoibWguandhZXJAZ21haWwuY29tIn0.4W9eo3M4YXAoiIh8rh10C4nl-YkKOz0LHB1u6ovKENU


###get User Detailes
GET http://localhost:3000/user
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2MDMxODk4NjgsImV4cCI6MTYwMzc5NDY2OCwiYXVkIjoiNWY4ZWJjNmNkYTFjMzAxMTBjOTQ2MmZmIiwiaXNzIjoibWguandhZXJAZ21haWwuY29tIn0.f53MZsGaN8cSD71D5r6xITbNzQTGlohb_PYh1mg4-_Q


###update message token
POST http://localhost:3000/user/message-token
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2MDI2ODYwOTIsImV4cCI6MTYwMzI5MDg5MiwiYXVkIjoiNWY4NzBjOGM1N2NhMDUwOTEwZmUyZjUwIiwiaXNzIjoibWguandhZXJAZ21haWwuY29tIn0.sTmYcZlQl3PM-QtFlN25XdDWxTMdIJUM2Fzf9nMkzTo
Content-Type: application/json

{
    "messageToken": "euKLJSAOas9SDKA98ASKJdjkajsCIV8AQWdsdlkfASASKJFMDlSOKJOSMAS1SLKLKSAD0ISLASLKD8KSkJKDJMnkdLLSJOIOskajdmIKSNS90ASmdKASJHFNANSKASJKSMdkDKFJMKFNFNMZLKJMFLKJAZXMJKLFJXZMFLKASASKFLK<LSKKDLK<DSKIKDospjdpAKKakJkJAjJAKj"
}


### get circle members
GET  http://localhost:3000/circle/members
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2MDMxODk4NjgsImV4cCI6MTYwMzc5NDY2OCwiYXVkIjoiNWY4ZWJjNmNkYTFjMzAxMTBjOTQ2MmZmIiwiaXNzIjoibWguandhZXJAZ21haWwuY29tIn0.f53MZsGaN8cSD71D5r6xITbNzQTGlohb_PYh1mg4-_Q


### set user location
POST http://localhost:3000/user/location
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2MDMxODk4NjgsImV4cCI6MTYwMzc5NDY2OCwiYXVkIjoiNWY4ZWJjNmNkYTFjMzAxMTBjOTQ2MmZmIiwiaXNzIjoibWguandhZXJAZ21haWwuY29tIn0.f53MZsGaN8cSD71D5r6xITbNzQTGlohb_PYh1mg4-_Q
Content-Type: application/json

{
    "latitude": "555555",
    "longitude": "444444"
}


### get circle members locations
GET http://localhost:3000/circle/members-locations
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2MDMxODk4NjgsImV4cCI6MTYwMzc5NDY2OCwiYXVkIjoiNWY4ZWJjNmNkYTFjMzAxMTBjOTQ2MmZmIiwiaXNzIjoibWguandhZXJAZ21haWwuY29tIn0.f53MZsGaN8cSD71D5r6xITbNzQTGlohb_PYh1mg4-_Q


### leave the circle
PATCH  http://localhost:3000/circle/leave
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2MDMxOTAwOTQsImV4cCI6MTYwMzc5NDg5NCwiYXVkIjoiNWY4ZWJkNGVkYTFjMzAxMTBjOTQ2MzAwIiwiaXNzIjoibWguandhZXJAZ21haWwuY29tIn0.4W9eo3M4YXAoiIh8rh10C4nl-YkKOz0LHB1u6ovKENU



### change circle admin
PATCH http://localhost:3000/circle/admin/5f8ebd4eda1c30110c946300
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2MDMxODk4NjgsImV4cCI6MTYwMzc5NDY2OCwiYXVkIjoiNWY4ZWJjNmNkYTFjMzAxMTBjOTQ2MmZmIiwiaXNzIjoibWguandhZXJAZ21haWwuY29tIn0.f53MZsGaN8cSD71D5r6xITbNzQTGlohb_PYh1mg4-_Q



### delete circle member
DELETE http://localhost:3000/circle/member/5f8ec145da1c30110c946302
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2MDMxODk4NjgsImV4cCI6MTYwMzc5NDY2OCwiYXVkIjoiNWY4ZWJjNmNkYTFjMzAxMTBjOTQ2MmZmIiwiaXNzIjoibWguandhZXJAZ21haWwuY29tIn0.f53MZsGaN8cSD71D5r6xITbNzQTGlohb_PYh1mg4-_Q



### change circle accessibilyt
PATCH http://localhost:3000/circle/accessibility
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2MDMxODk4NjgsImV4cCI6MTYwMzc5NDY2OCwiYXVkIjoiNWY4ZWJjNmNkYTFjMzAxMTBjOTQ2MmZmIiwiaXNzIjoibWguandhZXJAZ21haWwuY29tIn0.f53MZsGaN8cSD71D5r6xITbNzQTGlohb_PYh1mg4-_Q
Content-Type: image/jpeg

{
    "accessFlag": "false"
}


###mhj3
eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2MDMxOTExMDksImV4cCI6MTYwMzc5NTkwOSwiYXVkIjoiNWY4ZWMxNDVkYTFjMzAxMTBjOTQ2MzAyIiwiaXNzIjoibWguandhZXJAZ21haWwuY29tIn0.qz4gZAG6h10fFrcQ20buTiK7MBlBgJC2z-VBLENroYo
5f8ec145da1c30110c946302

###mhj2
eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2MDMxOTAwOTQsImV4cCI6MTYwMzc5NDg5NCwiYXVkIjoiNWY4ZWJkNGVkYTFjMzAxMTBjOTQ2MzAwIiwiaXNzIjoibWguandhZXJAZ21haWwuY29tIn0.4W9eo3M4YXAoiIh8rh10C4nl-YkKOz0LHB1u6ovKENU
5f8ebd4eda1c30110c946300

###mhj1
eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2MDMxODk4NjgsImV4cCI6MTYwMzc5NDY2OCwiYXVkIjoiNWY4ZWJjNmNkYTFjMzAxMTBjOTQ2MmZmIiwiaXNzIjoibWguandhZXJAZ21haWwuY29tIn0.f53MZsGaN8cSD71D5r6xITbNzQTGlohb_PYh1mg4-_Q
5f8ebc6cda1c30110c9462ff